import fs from 'fs/promises'
import path, { join } from 'path'

export const takeLab = (newTaking, arrayPatient) => {

  const labRecordMaker = []
  for (let i = 0; i < arrayPatient.length; i++) {
    newTaking = {
      ...newTaking,
      IDMUESTR: arrayPatient[i][0],
      NOMBRE: arrayPatient[i][1],
      APELLIDO: arrayPatient[i][2],
      MODO: arrayPatient[i][3],
      FECHA: arrayPatient[i][4],
      HORA: arrayPatient[i][5],
      ESTDEMUESTRA: arrayPatient[i][6],
      'WBC(10^9/L)': arrayPatient[i][7],
      'NEU#(10^9/L)': arrayPatient[i][8],
      'LYM#(10^9/L)': arrayPatient[i][9],
      'MON#(10^9/L)': arrayPatient[i][10],
      'EOS#(10^9/L)': arrayPatient[i][11],
      'BAS#(10^9/L)': arrayPatient[i][12],
      'NEU%(%)': arrayPatient[i][13],
      'LYM%(%)': arrayPatient[i][14],
      'MON%(%)': arrayPatient[i][15],
      'EOS%(%)': arrayPatient[i][16],
      'BAS%(%)': arrayPatient[i][17],
      'RBC(10^12/L)': arrayPatient[i][18],
      'HGB(G/DL)': arrayPatient[i][19],
      'HCT(%)': arrayPatient[i][20],
      'MCV(FL)': arrayPatient[i][21],
      'MCH(PG)': arrayPatient[i][22],
      'MCHC(G/DL)': arrayPatient[i][23],
      'RDW-CV(%)': arrayPatient[i][24],
      'RDW-SD(FL)': arrayPatient[i][25],
      'PLT(10^9/L)': arrayPatient[i][26],
      'MPV(FL)': arrayPatient[i][27],
      'PDW()': arrayPatient[i][28],
      'PCT(ML/L)': arrayPatient[i][29],
      'ALY#(10^9/L)': arrayPatient[i][30],
      'ALY%(%)': arrayPatient[i][31],
      'LIC#(10^9/L)': arrayPatient[i][32],
      'LIC%( )': arrayPatient[i][33],
      'BLAST#(10^9/L)': arrayPatient[i][34],
      'BLAST%(%)': arrayPatient[i][35],
      'NRBC#(10^9/L)': arrayPatient[i][36],
      'NRBC%(%)': arrayPatient[i][37],
      'PLTCLUMP#(10^9/L)': arrayPatient[i][38],
      'PLTCLUMP%( )': arrayPatient[i][39],
      'LIP#(10^9/L)': arrayPatient[i][40],
      'LIP%( )': arrayPatient[i][41],
      'NLR( )': arrayPatient[i][42],
      'PLR( )': arrayPatient[i][43],
      IDPAC: arrayPatient[i][44],
      SEXO: arrayPatient[i][45],
      TIPOPAC: arrayPatient[i][46],
      'GRUPODEREF.': arrayPatient[i][47],
      'FECHANAC.': arrayPatient[i][48],
      EDAD: arrayPatient[i][49],
      DPTO: arrayPatient[i][50],
      'N?CAMA': arrayPatient[i][51],
      FECHADETRAZADO: arrayPatient[i][52],
      HORADETRAZADO: arrayPatient[i][53],
      FECHAENTREGA: arrayPatient[i][54],
      HORENTR: arrayPatient[i][55],
      'M��DICOCL��NICO': arrayPatient[i][56],
      OPERADOR: arrayPatient[i][57],
      VALIDADOPOR: arrayPatient[i][58],
      COMENTARIOS: arrayPatient[i][59],
      MENSAJEWBC: arrayPatient[i][60],
      MENSAJERBC: arrayPatient[i][61],
      MENSAJEPLT: arrayPatient[i][62],
      'GRUPOSANGU��NEO': arrayPatient[i][63],
      ESR: arrayPatient[i][64],
      'PAR��M.MICROSC��PICOS': arrayPatient[i][5],
    }
    labRecordMaker.push(newTaking)
  }
  console.log(labRecordMaker)
}
